CREATE TABLE CANDIDATOS (
    NUM_BOLETA VARCHAR2(30) NOT NULL,
    NOMBRE VARCHAR2(30) NOT NULL,
    APELL_PATERNO VARCHAR2(30) NOT NULL,
    APELL_MAT VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    CELULAR VARCHAR2(15) NOT NULL,
    CARRERA VARCHAR2(20) NOT NULL,
    GENERACION VARCHAR2(8) NOT NULL,
    DIRECTOR_TESIS VARCHAR2(50) NOT NULL,
    TEMA_TESIS VARCHAR2(60) NOT NULL,
    TRABAJA VARCHAR2(4) ,
    LUGAR_TRABAJO VARCHAR2(60),
    HORARIO_TRABAJO VARCHAR2(30),
    IMAGEN BLOB NOT NULL,
    CONSTRAINT PK_CANDIDATOS PRIMARY KEY(NUM_BOLETA)
);


CREATE TABLE ASESORES(
NOMBRE VARCHAR2(30) NOT NULL,
APELL_PATERNO VARCHAR2(30) NOT NULL,
APELL_MAT VARCHAR2(30) NOT NULL,
CUBICULO VARCHAR2(9) NOT NULL,
EMAIL VARCHAR2(30) NOT NULL,
HORARIO VARCHAR2(30) NOT NULL,
CONSTRAINT PK_ASESORES PRIMARY KEY (EMAIL) 
);

CREATE TABLE GRUPOS(
ID_GRUPO NUMBER NOT NULL,
NUM_BOLETA VARCHAR2(30) NOT NULL,
CONSTRAINT PK_GRUPO PRIMARY KEY(ID_GRUPO),
CONSTRAINT NUM_BOLETA FOREIGN KEY (NUM_BOLETA) REFERENCES CANDIDATOS(NUM_BOLETA)
);


CREATE TABLE DETALL_GRUPOS(
ID_GRUPO NUMBER  NOT NULL,
NUM_BOLETA VARCHAR2(30) NOT NULL,
CONSTRAINT FK_GRUPO  FOREIGN KEY(ID_GRUPO)REFERENCES GRUPOS(ID_GRUPO),
CONSTRAINT NUM_BOLETA FOREIGN KEY (NUM_BOLETA) REFERENCES CANDIDATOS(NUM_BOLETA)
);

CREATE TABLE GRUPOS(
ID_GRUPO  NUMBER NOT NULL,
CONSTRAINT PK_DETALGRPUP PRIMARY  KEY(ID_GRUPO) 
);

commit;
 select*from ASESORES;
 SELECT* FROM CANDIDATOS;
 SELECT * from DETALL_GRUPOS;
 drop table GRUPOS;
 SELECT COUNT(*) AS NUMGRUP FROM GRUPOS;
  DROP TABLE DETALL_GRUPOS;
 .
